defaults:
  - _self_
  - dataset: ogbn-arxiv

version: 'Graph Project v1'

hydra:
  run:
    dir: ./outputs/${dataset.task}/${dataset.dataset_name}/${model_type}/${now:%Y-%m-%d}/${now:%H-%M-%S}

model_type: GNN
device: 'cpu'
runs: 1
debug: False
