defaults:
  - _self_
  - dataset: ogbn-arxiv

version: 'Graph Project v1'

hydra:
  run:
    dir: ./outputs/${task}/${dataset.dataset_name}/${model_type}/${now:%Y-%m-%d}/${now:%H-%M-%S}

model_type: DownStream
device: 'cpu'
runs: 1
task: 'NodeClassification'
debug: False
