defaults:
  - _self_
  - model: GNN

version: 'Graph Project v1'

hydra:
  run:
    dir: ./outputs/${task}/${dataset}/${model.model_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

dataset: 'ogbn-arxiv'
task: 'NodeClassification'
device: 'cpu'
seed: 42
