defaults:
  - _self_
  - model: Node2Vec

version: 'Graph Project v1'

hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

dataset: 'ogbn-arxiv'
task: 'NodeClassification'
device: 'cpu'
seed: 42
