dataset_name: 'Cora'
task: 'LinkPrediction'
metrics: ['hits@10','hits@50','hits@100','acc','auc']
track_metric: 'acc'

DownStream:
  saved_embeddings: False
  using_features: True
  use_spectral: False
  random: False
  K: 16
  training:
    epochs: 200
    num_layers: 2
    dropout: 0.0
    lr: 0.01
    hidden_channels: 128
    batch_size: 512

Node2Vec:
  training:
    embedding_dim: 8
    walk_length: 80
    context_size: 20
    walks_per_node: 10
    epochs: 10
    lr: 0.01
    batch_size: 256
    num_negative_samples: 1
    sparse: True
    num_workers: 4

GNN:
  model: 'GraphSage'
  extra_info: False
  training:
    hidden_channels: 8
    num_layers: 2
    dropout: 0.0
    lr: 0.01
    epochs: 300
    batch_size: 1024
    weight_decay: 0


Shallow:
  training:
    lr: 0.01
    epochs: 1500
    init_beta: 0.0
    embedding_dim: 8
    init: 'laplacian'
    decode_type: 'dist'
    batch_size: 256
    train_batch: False
    weight_decay: 0.00005



combined:
  type: 'comb3'
  comb1:
    training:
      shallow_lr: 0.1
      init_beta: 0.0
      embedding_dim: 64
      init: 'laplacian'
      decode_type: 'dist'

      direct: True
      deep_model: 'GraphSage'
      deep_hidden_channels: 256
      deep_lr: 0.01
      deep_out_dim: 256
      deep_num_layers: 3
      deep_dropout: 0.1
      deep_decode: 'dist'
      gamma: 0.0

      balance: False
      warm_start: 100
      joint_train: 100
      shallow_lr_joint: 0.1
      deep_lr_joint: 0.001
      lambda_lr: 0.01
      lambda_: 1.0
      batch_size: 512
      direction: 'shallow_first'
      shallow_frozen_epochs: 0
      deep_frozen_epochs: 0

  comb2:
    training:
      shallow_lr: 0.1
      init_beta: 0.0
      embedding_dim: 8
      init: 'laplacian'
      decode_type: 'dist'
      weight_decay_shallow: 0.00005


      deep_model: 'GraphSage'
      deep_hidden_channels: 8
      deep_lr: 0.01
      deep_out_dim: 8
      deep_num_layers: 2
      deep_dropout: 0.0
      weight_decay_deep: 0.0

      balance: False
      warm_start: 500
      joint_train: 300
      shallow_lr_joint: 0.1
      deep_lr_joint: 0.01
      lambda_lr: 0.01
      lambda_: 1.0
      batch_size: 512
      direction: 'deep_first'
      shallow_frozen_epochs: 0
      deep_frozen_epochs: 200

  comb3:
    training:
      shallow_lr: 0.1
      init_beta: 0.0
      embedding_dim: 8
      init: 'laplacian'
      decode_type: 'dist'
      weight_decay_shallow: 0.00005


      deep_model: 'GCN'
      deep_hidden_channels: 8
      deep_lr: 0.01
      deep_out_dim: 8
      deep_num_layers: 2
      deep_dropout: 0.0

      warm_start: 500
      joint_train: 300
      shallow_lr_joint: 0.1
      deep_lr_joint: 0.01
      lambda_lr: 0.01
      lambda_: 1.0
      batch_size: 512
      direction: 'deep_first'
      shallow_frozen_epochs: 0
      deep_frozen_epochs: 300


      MLP_HIDDEN_CHANNELS: 16
      MLP_LAYERS: 2
      MLP_DROPOUT: 0.0

  comb4:
    training:
      shallow_lr: 0.1
      init_beta: 0.0
      embedding_dim: 64
      init: 'random'
      decode_type: 'dist'


      deep_model: 'GCN'
      deep_hidden_channels: 256
      deep_lr: 0.01
      deep_out_dim: 256
      deep_num_layers: 3
      deep_dropout: 0.0
      direct: True
      gamma: 0.0
      deep_decode: 'dist'


      balance: False
      warm_start: 1
      joint_train: 1
      shallow_lr_joint: 0.1
      deep_lr_joint: 0.01
      lambda_lr: 0.01
      lambda_: 1.0
      batch_size: 512
      direction: 'shallow_first'
      shallow_frozen_epochs: 0
      deep_frozen_epochs: 0
