dataset_name: 'ogbl-citation2'
task: 'LinkPrediction'
metrics: ['mrr']
track_metric: 'mrr'

DownStream:
  saved_embeddings: False
  using_features: True
  use_spectral: False
  random: False
  K: 16
  training:
    epochs: 100
    num_layers: 3
    dropout: 0.0
    lr: 0.01
    hidden_channels: 256
    batch_size: 65536
    weight_decay: 0

Node2Vec:
  training:
    embedding_dim: 128
    walk_length: 40
    context_size: 20
    walks_per_node: 10
    epochs: 1
    lr: 0.01
    batch_size: 256
    num_negative_samples: 1
    sparse: True
    num_workers: 4

GNN:
  model: 'GraphSage'
  extra_info: False
  training:
    hidden_channels: 256
    num_layers: 3
    dropout: 0.0
    lr: 0.0005
    epochs: 50
    use_valedges: False
    batch_size: 65536
    weight_decay: 0


Shallow:
  training:
    lr: 0.1
    epochs: 200
    init_beta: 0.0
    embedding_dim: 64
    init: 'random'
    decode_type: 'dist'
    batch_size: 65536
    train_batch: False
    weight_decay: 0
