dataset_name: 'ogbn-arxiv'
task: 'NodeClassification'
metrics: ['acc','f1-micro','f1-macro']
track_metric: 'acc'

DownStream:
  saved_embeddings: False
  using_features: True
  use_spectral: False
  random: False
  K: 16
  training:
    epochs: 100
    num_layers: 3
    dropout: 0.5
    lr: 0.01
    hidden_channels: 256
    batchnorm: True
    weight_decay: 0

Node2Vec:
  training:
    embedding_dim: 128
    walk_length: 80
    context_size: 20
    walks_per_node: 10
    epochs: 5
    lr: 0.01
    batch_size: 256
    num_negative_samples: 1
    sparse: True
    num_workers: 4

GNN:
  model: 'GraphSage'
  extra_info: False
  training:
    hidden_channels: 256
    num_layers: 3
    dropout: 0.5
    lr: 0.01
    epochs: 5
    use_valedges: False
    batchnorm: True
    weight_decay: 0


Shallow:
  training:
    lr: 0.1
    epochs: 50
    init_beta: 0.0
    embedding_dim: 2
    init: 'laplacian'
    decode_type: 'dist'
    train_batch: False
    batch_size: 65536
    weight_decay: 0
