model_name: Node2Vec
model: 'Node2Vec'

training:
  embedding_dim: 128
  walk_length: 80
  context_size: 20
  walks_per_node: 10
  epochs: 5
  lr: 0.01
  batch_size: 256
  num_negative_samples: 1
  sparse: True
  num_workers: 4
